"""
Streamlit frontend application for the Wood Group HR Assistant.
Provides a modern, interactive chat UI and communicates with the FastAPI backend.
"""

import streamlit as st
import requests

# Page configuration
st.set_page_config(page_title="HR Assistant", page_icon="📘", layout="wide")

# Custom CSS (loaded from external file)
try:
    with open("style.css", "r") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
except FileNotFoundError:
    pass

# Sidebar
with st.sidebar:
    st.markdown("# HR Assistant")
    st.markdown("A specialised AI assistant trained strictly on the Wood Group UK Leave & Absence policies.")
    
    st.markdown("### CAPABILITIES")
    st.markdown("📄 Paternity & Maternity Procedures")
    st.markdown("📄 Shared Parental Leave")
    st.markdown("📄 Ordinary Parental Leave")
    st.markdown("📄 Sickness Absence")
    st.markdown("📄 Adoption Procedures")
    st.markdown("📄 General Leave of Absence")
    
    st.markdown("---")
    st.markdown("### SETTINGS")
    if "selected_provider" not in st.session_state:
        st.session_state.selected_provider = "Groq"
    model_provider = st.selectbox("LLM Provider", ["Groq", "Gemini"], key="selected_provider")
    
    st.markdown("<br><br>", unsafe_allow_html=True)
    if st.button("🗑️ Clear Conversation", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

# Initialize Chat History
if "messages" not in st.session_state or not st.session_state.messages:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hello! I am your Wood Group HR Assistant. How can I help you with your UK leave or absence questions today?", "sources": None}
    ]

# Display chat messages
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("sources"):
            with st.expander(f"📄 View Source Documents ({len(msg['sources'])})"):
                for idx, doc in enumerate(msg["sources"]):
                    st.markdown(f"**Source {idx+1}:** `{doc.get('source', 'Unknown')}`")
                    st.markdown(f"*{doc.get('content', '')}*")
                    st.markdown("---")

import os

# Define the dynamic API base URL (defaults to localhost for local testing)
API_BASE_URL = os.environ.get("API_BASE_URL", "http://127.0.0.1:8000")

# Render's 'hostport' property drops the schema, so we must prepend http:// if missing
# (We use http instead of https because this routes over Render's internal private network)
if not API_BASE_URL.startswith("http"):
    API_BASE_URL = f"http://{API_BASE_URL}"

API_URL = f"{API_BASE_URL}/chat"

# --- Cold Start Mitigation ---
@st.cache_data(ttl=600)
def wake_backend() -> None:
    """
    Sends a silent background ping to the FastAPI /health endpoint.
    This helps mitigate Render's 'cold start' sleep by waking the server
    as soon as the frontend is loaded by the user.
    """
    try:
        requests.get(f"{API_BASE_URL}/health", timeout=5)
    except:
        pass

# Fire a silent ping when the app loads to wake up the backend early
wake_backend()
# -----------------------------

# Handle user input
if prompt_input := st.chat_input("Ask a question about HR policies..."):
    # Add user message to state
    st.session_state.messages.append({"role": "user", "content": prompt_input})
    with st.chat_message("user"):
        st.markdown(prompt_input)
        
    with st.chat_message("assistant"):
        with st.spinner("Searching policies..."):
            try:
                # Call the REST API Backend dynamically
                response = requests.post(
                    API_URL,
                    json={"question": prompt_input, "provider": model_provider},
                    timeout=60
                )
                response.raise_for_status()
                data = response.json()
                
                answer = data["answer"]
                sources = data["sources"]
                used_provider = data.get("used_provider", model_provider)
                
                if used_provider != model_provider:
                    st.success(f"⚠️ **Fallback Triggered:** The {model_provider} model was currently unavailable due to rate limits. Your answer was reliably generated by the {used_provider} fallback model!")
                    # Automatically switch the UI selectbox to the working model for future queries
                    st.session_state.selected_provider = used_provider
                
                st.markdown(answer)
                
                if sources:
                    with st.expander(f"📄 View Source Documents ({len(sources)})"):
                        for idx, doc in enumerate(sources):
                            st.markdown(f"**Source {idx+1}:** `{doc.get('source', 'Unknown')}`")
                            st.markdown(f"*{doc.get('content', '')}*")
                            st.markdown("---")
                
                st.session_state.messages.append({"role": "assistant", "content": answer, "sources": sources})
            except requests.exceptions.HTTPError as e:
                # If it's a 502, 503, or 504, it's a Render Cold Start or Gateway timeout
                if e.response.status_code in [502, 503, 504]:
                    st.warning("⏳ The backend AI server is currently waking up from sleep mode (this takes about 50 seconds on the free tier). Please wait a moment and submit your question again!")
                else:
                    # It's a real API error (e.g. 500 Internal Server Error)
                    try:
                        error_detail = e.response.json().get("detail", str(e))
                    except:
                        error_detail = str(e)
                    st.error(f"Backend API Error: {error_detail}")
            except requests.exceptions.RequestException as e:
                # This catches generic network errors (like DNS failures or connection timeouts)
                st.warning("⏳ The backend AI server is currently waking up from sleep mode. Please wait a moment and try again!")
            except Exception as e:
                st.error(f"An unexpected error occurred: {e}")

# Disclaimer at the bottom
st.markdown('<div class="disclaimer-text">Wood Group HR Assistant can make mistakes. Verify important information with your P&O representative.</div>', unsafe_allow_html=True)

