"""
A reporting utility to calculate and display performance metrics.

This script reads the `evaluation_results.csv` file generated by `evaluate.py`
and computes summary statistics for latency and errors.

It provides a quick way to view the performance summary without needing to
re-run the entire evaluation process.
"""
import csv
import os
import numpy as np

latencies = []
errors = 0
total = 0

# Construct the absolute path to the CSV file in the project root directory
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
csv_path = os.path.join(ROOT_DIR, "evaluation_results.csv")

try:
    with open(csv_path, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            total += 1
            # Corrected the column name from 'Latency (s)' to 'Latency'
            lat = row.get('Latency', '')
            if lat:
                try:
                    latencies.append(float(lat))
                except (ValueError, TypeError):
                    pass
            err = row.get('Error', '')
            if err and err.strip():
                errors += 1
except FileNotFoundError:
    print(f"[ERROR] The evaluation results file was not found at: {csv_path}")
    print("Please run 'python scripts/evaluate.py' first to generate the results.")
    exit()

if latencies:
    latencies_np = np.array(latencies)
    avg = np.mean(latencies_np)
    p50 = np.percentile(latencies_np, 50)
    p95 = np.percentile(latencies_np, 95)
    
    print(f"Total questions: {total}")
    print(f"Avg Latency: {avg:.2f}s")
    print(f"p50 Latency: {p50:.2f}s")
    print(f"p95 Latency: {p95:.2f}s")
    print(f"Errors: {errors}")
else:
    print("No valid latency data found in the results file.")
